// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductService.Data;

#nullable disable

namespace ProductService.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260807133603_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Men's Clothing & Accessories",
                            ImageUrl = "https://images.unsplash.com/photo-1490578474895-699bc4e2cf59",
                            Name = "Men"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Women's Fashion & Apparel",
                            ImageUrl = "https://images.unsplash.com/photo-1483985988355-763728e1935b",
                            Name = "Women"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kids' Wear & Toys",
                            ImageUrl = "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea",
                            Name = "Kids"
                        });
                });

            modelBuilder.Entity("ProductService.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int?>("SubcategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "UrbanWear",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium 100% cotton crewneck t-shirt.",
                            ImageUrl = "https://images.unsplash.com/photo-1521572267360-ee0c2909d518",
                            Name = "Classic Black Tee",
                            Price = 29.99m,
                            SellerId = 1,
                            SubcategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Brand = "DenimCo",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable stretch denim jeans.",
                            ImageUrl = "https://images.unsplash.com/photo-1542272604-780c36856842",
                            Name = "Slim Fit Blue Jeans",
                            Price = 59.99m,
                            SellerId = 1,
                            SubcategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            Brand = "BloomFashion",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight floral print midi dress.",
                            ImageUrl = "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1",
                            Name = "Floral Summer Dress",
                            Price = 49.99m,
                            SellerId = 2,
                            SubcategoryId = 3
                        });
                });

            modelBuilder.Entity("ProductService.Models.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Casual & Graphic Tees",
                            Name = "T-Shirts"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Denim Trousers & Pants",
                            Name = "Jeans"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Evening & Casual Dresses",
                            Name = "Dresses"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Blouses & Shirts",
                            Name = "Tops"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Shirts & Shorts",
                            Name = "Boys Wear"
                        });
                });

            modelBuilder.Entity("ProductService.Models.Product", b =>
                {
                    b.HasOne("ProductService.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductService.Models.Subcategory", "Subcategory")
                        .WithMany("Products")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("ProductService.Models.Subcategory", b =>
                {
                    b.HasOne("ProductService.Models.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductService.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("ProductService.Models.Subcategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
