#spring.application.name=AIService
#
#server.port=8084
#
## Ollama Server
#spring.ai.ollama.base-url=http://localhost:11434
#
## AI Model
#spring.ai.ollama.chat.model=llama3
#
## Optional
#spring.ai.chat.client.enabled=true

spring.application.name=AIService

server.port=8084

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2

spring.ai.chat.client.enabled=true