spring.application.name=ApiGateway
server.port=8080

# Eureka Client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true


# =========================
# Product Service
# =========================

spring.cloud.gateway.server.webmvc.routes[0].id=product-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/products/**


# =========================
# Order Service
# =========================

spring.cloud.gateway.server.webmvc.routes[1].id=order-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/orders/**


# =========================
# User Service
# =========================

spring.cloud.gateway.server.webmvc.routes[2].id=user-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/auth/**

# =========================
# Wishlist Service
# =========================

spring.cloud.gateway.server.webmvc.routes[3].id=wishlist-service
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/wishlist/**

# =========================
# Cart Service
# =========================

spring.cloud.gateway.server.webmvc.routes[4].id=cart-service
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/cart/**

# =========================
# User Profile Service
# =========================

spring.cloud.gateway.server.webmvc.routes[5].id=user-profile-service
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/users/**

# =========================
# Inventory Service
# =========================

spring.cloud.gateway.server.webmvc.routes[6].id=inventory-service
spring.cloud.gateway.server.webmvc.routes[6].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/inventory/**

# =========================
# Category Service
# =========================

spring.cloud.gateway.server.webmvc.routes[7].id=category-service
spring.cloud.gateway.server.webmvc.routes[7].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/categories/**

# =========================
# SubCategory Service
# =========================

spring.cloud.gateway.server.webmvc.routes[8].id=subcategory-service
spring.cloud.gateway.server.webmvc.routes[8].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/subcategories/**


# =========================
# CORS
# =========================

spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true